services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: MYgmeSr5HUT5
      APP_USER: app
      APP_USER_PASSWORD: MYgmeSr5HUT5
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'SELECT 1 FROM DUAL;' | sqlplus -s SYSTEM/MYgmeSr5HUT5@localhost/freepdb1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./oracle/init.sql:/container-entrypoint-initdb.d/init.sql:ro
    restart: always

  oracledb-exporter:
    build:
      context: ./exporter
      dockerfile: Dockerfile
    ports:
      - "9161:9161"
    environment:
      - DATA_SOURCE_NAME=oracle://exporter:exporter_password@oracle-db:1521/freepdb1
    depends_on:
      - oracle-db
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      - oracledb-exporter
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=nGLzt7XRm247
    depends_on:
      - prometheus
    volumes:
      - ./grafana/data:/var/lib/grafana
    restart: always

volumes:
  prometheus_data:
