ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

INSERT INTO users (name, email) VALUES ('Alice', 'alice@example.com');
INSERT INTO users (name, email) VALUES ('Bob', 'bob@example.com');
INSERT INTO users (name, email) VALUES ('Charlie', 'charlie@example.com');

INSERT INTO posts (user_id, title, content) VALUES (1, 'Welcome Post', 'This is Alice''s first post!');
INSERT INTO posts (user_id, title, content) VALUES (1, 'Another Post', 'Alice is enjoying writing posts.');
INSERT INTO posts (user_id, title, content) VALUES (2, 'Hello World', 'Bob is here with his first post!');
INSERT INTO posts (user_id, title, content) VALUES (3, 'Greetings', 'Charlie has joined the platform.');

CREATE USER exporter IDENTIFIED BY "exporter_password";

GRANT CONNECT TO exporter;
GRANT SELECT ANY DICTIONARY TO exporter;
GRANT SELECT ON V_$SESSION TO exporter;
GRANT SELECT ON V_$SYSSTAT TO exporter;
GRANT SELECT ON V_$INSTANCE TO exporter;
GRANT SELECT ON V_$LOG TO exporter;
GRANT SELECT ON V_$LOG_HISTORY TO exporter;
GRANT SELECT ON V_$SYSTEM_EVENT TO exporter;
GRANT SELECT ON V_$EVENT_NAME TO exporter;
GRANT SELECT ON V_$WAITCLASSMETRIC TO exporter;
GRANT SELECT ON V_$SYS_TIME_MODEL TO exporter;
GRANT SELECT ON V_$SESSTAT TO exporter;
GRANT SELECT ON V_$SQL TO exporter;
GRANT SELECT ON V_$SQLAREA TO exporter;

COMMIT;
